<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#0F172A">
    <meta name="description" content="Zazu EMP — event operations management for jobs, catering, equipment, quotes and finance.">
    <title>Zazu EMP · Event Operations Management</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@500;600;700;800&display=swap');
        :root{--ink:#0F172A;--body:#334155;--muted:#64748B;--blue:#1E40AF;--sapphire:#2563EB;--glow:#3B82F6;--soft:#EFF6FF;--canvas:#F8FAFC;--line:#E2E8F0;--card:#fff}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--canvas);font-family:Manrope,ui-sans-serif,system-ui,sans-serif}
        body:before{content:"";position:fixed;inset:0;z-index:-2;background:linear-gradient(180deg,rgba(248,250,252,.84),rgba(248,250,252,.96)),url('/images/Background-ZAZU.jpg') center/cover no-repeat}
        body:after{content:"";position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(circle at 78% 12%,rgba(59,130,246,.12),transparent 28%),linear-gradient(90deg,transparent 0 70%,rgba(255,255,255,.22))}
        a{text-decoration:none;color:inherit}button{font:inherit}.mono{font-family:"DM Mono",ui-monospace,monospace}.site{width:min(1380px,calc(100% - 40px));margin:auto}
        .top{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(226,232,240,.82);backdrop-filter:blur(16px)}
        .brand{display:flex;align-items:center;gap:11px}.mark{width:36px;height:36px;display:grid;place-items:center;border-radius:9px;background:var(--blue);color:#fff;font-weight:800;box-shadow:0 8px 20px rgba(30,64,175,.2)}.brand strong{display:block;letter-spacing:-.04em}.brand span:last-child{display:block;color:var(--muted);font:500 9px "DM Mono";letter-spacing:.08em;text-transform:uppercase;margin-top:2px}
        .topnav{display:flex;align-items:center;gap:6px}.topnav a{padding:9px 11px;border-radius:7px;color:var(--muted);font-size:11px;font-weight:700}.topnav a:hover{background:#fff;color:var(--ink)}.topnav .launch{padding:11px 15px;background:var(--blue);color:#fff;box-shadow:0 7px 16px rgba(30,64,175,.16)}
        .hero{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(460px,.92fr);gap:clamp(40px,7vw,100px);align-items:center;min-height:calc(100vh - 76px);padding:72px 0 88px}
        .eyebrow{display:flex;align-items:center;gap:8px;color:var(--blue);font:500 10px "DM Mono";letter-spacing:.13em;text-transform:uppercase}.eyebrow:before{content:"";width:24px;height:1px;background:currentColor}
        h1{max-width:780px;margin:18px 0;font-size:clamp(48px,6.4vw,88px);line-height:.93;letter-spacing:-.065em}h1 em{font-style:normal;color:var(--blue)}.hero-copy{max-width:650px;color:var(--body);font-size:17px;line-height:1.7}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:28px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:44px;padding:0 16px;border:1px solid var(--line);border-radius:7px;background:#fff;color:var(--ink);font-size:11px;font-weight:800}.btn.primary{border-color:var(--blue);background:var(--blue);color:#fff;box-shadow:0 9px 20px rgba(30,64,175,.17)}.btn:hover{transform:translateY(-1px)}.hero-note{margin-top:18px;color:var(--muted);font:500 9px "DM Mono";letter-spacing:.05em}
        .control-card{overflow:hidden;border:1px solid rgba(203,213,225,.95);border-radius:14px;background:rgba(255,255,255,.91);box-shadow:0 25px 70px rgba(15,23,42,.12);backdrop-filter:blur(18px)}.control-head{display:flex;justify-content:space-between;padding:13px 15px;border-bottom:1px solid var(--line);font:500 9px "DM Mono";letter-spacing:.07em}.online{display:flex;gap:6px;align-items:center;color:#166534}.online i{width:6px;height:6px;border-radius:50%;background:#16A34A;box-shadow:0 0 0 4px rgba(22,163,74,.1)}
        .telemetry{display:grid;grid-template-columns:repeat(5,1fr);border-bottom:1px solid var(--line)}.telemetry div{padding:16px 12px;border-right:1px solid var(--line)}.telemetry div:last-child{border:0}.telemetry small{display:block;color:var(--muted);font:500 8px "DM Mono";text-transform:uppercase}.telemetry strong{display:block;margin-top:7px;font:500 22px "DM Mono"}
        .record{display:grid;grid-template-columns:1.35fr .8fr .9fr;gap:20px;padding:20px}.record small,.record-label{display:block;color:var(--muted);font:500 8px "DM Mono";text-transform:uppercase}.record strong{display:block;margin-top:7px;font-size:13px}.record .ref{font:500 11px "DM Mono";word-break:break-all}.record-meta{margin-top:5px;color:var(--muted);font-size:10px}.tag{display:inline-flex;margin-top:7px;padding:4px 6px;border-radius:999px;background:#FEF3C7;color:#92400E;font:500 8px "DM Mono"}
        .flow{display:flex;align-items:center;gap:6px;padding:11px 15px;background:#0F172A;color:#CBD5E1;font:500 8px "DM Mono";overflow:auto;white-space:nowrap}.flow b{color:#93C5FD;font-weight:500}
        .section{padding:105px 0;border-top:1px solid rgba(226,232,240,.8)}.section-head{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:30px}.section h2{max-width:720px;margin:10px 0 0;font-size:clamp(31px,4vw,54px);line-height:.98;letter-spacing:-.055em}.intro{max-width:480px;color:var(--muted);font-size:13px;line-height:1.7}
        .bento{display:grid;grid-template-columns:1.35fr .65fr;grid-template-rows:auto auto;gap:12px}.feature{padding:28px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.88);box-shadow:0 10px 28px rgba(15,23,42,.045)}.feature.large{grid-row:span 2;min-height:410px;background:linear-gradient(145deg,#fff,#EFF6FF)}.num{font:500 9px "DM Mono";color:var(--blue)}.feature h3{margin:54px 0 10px;font-size:24px;letter-spacing:-.035em}.feature p{margin:0;color:var(--muted);font-size:12px;line-height:1.7}.mini{min-height:195px}.mini h3{margin-top:32px}
        .compare{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#fff}.compare>article{padding:32px}.compare>article+article{border-left:1px solid var(--line);background:var(--ink);color:#fff}.compare h3{margin:0 0 20px;font:500 10px "DM Mono";letter-spacing:.12em;text-transform:uppercase}.compare ul{list-style:none;padding:0;margin:0;display:grid;gap:13px}.compare li{color:var(--body);font-size:13px;line-height:1.55}.compare li:before{content:"—";margin-right:9px;color:var(--sapphire)}.compare>article+article li{color:#CBD5E1}
        .closing{padding:90px 0}.closing-box{display:flex;align-items:center;justify-content:space-between;gap:30px;padding:38px;border-radius:14px;background:var(--blue);color:#fff;box-shadow:0 20px 50px rgba(30,64,175,.2)}.closing-box h2{margin:8px 0;font-size:34px;letter-spacing:-.045em}.closing-box p{margin:0;color:#DBEAFE;font-size:12px}.closing-box .btn{border-color:#fff;background:#fff;color:var(--blue)}
        footer{display:flex;justify-content:space-between;padding:22px 0;border-top:1px solid var(--line);color:var(--muted);font:500 8px "DM Mono";letter-spacing:.06em}
        @media(max-width:920px){.hero{grid-template-columns:1fr;min-height:auto;padding-top:60px}.bento{grid-template-columns:1fr}.feature.large{grid-row:auto}.section-head{display:block}.intro{margin-top:15px}.closing-box{display:block}.closing-box .btn{margin-top:20px}}
        @media(max-width:640px){.site{width:min(100% - 24px,1380px)}.top{height:auto;padding:14px 0}.topnav a:not(.launch){display:none}.hero{padding:48px 0 65px}h1{font-size:48px}.telemetry{grid-template-columns:repeat(2,1fr)}.telemetry div:nth-child(2n){border-right:0}.record{grid-template-columns:1fr}.compare{grid-template-columns:1fr}.compare>article+article{border-left:0;border-top:1px solid #334155}footer{display:block}.footer-right{margin-top:8px}}
    </style>
</head>
<body>
<div class="site">
<header class="top">
    <a href="{{ url('/') }}" class="brand"><span class="mark">Z</span><span><strong>ZAZU</strong><span>Event Management Platform</span></span></a>
    <nav class="topnav" aria-label="Public navigation"><a href="#capabilities">Capabilities</a><a href="#difference">Why Zazu</a><a class="launch" href="{{ auth()->check() ? route('dashboard') : route('login') }}">Launch workspace <span>↗</span></a></nav>
</header>
<main>
<section class="hero">
<div><div class="eyebrow">Event operations command system</div><h1>Precision command for <em>events, catering &amp; equipment hire.</em></h1><p class="hero-copy">Zazu EMP brings the operational record to the centre of the business—connecting jobs, customers, services, resources, preparation and commercial activity without turning the team into spreadsheet administrators.</p><div class="actions"><a class="btn primary" href="{{ auth()->check() ? route('dashboard') : route('login') }}">Launch Rosco ICT Workspace <span>→</span></a><a class="btn" href="#capabilities">Explore the operating model</a></div><div class="hero-note">LOCAL-FIRST WORKSPACE · OPERATIONS · RESOURCES · COMMERCIAL · CONTROL</div></div>
<div class="control-card" aria-label="Live workspace preview">
<div class="control-head"><span>ROSCO ICT / LIVE WORKSPACE</span><span class="online"><i></i>ONLINE</span></div>
<div class="telemetry">
<div><small>All work</small><strong>{{ str_pad((string)$telemetry['all_work'],2,'0',STR_PAD_LEFT) }}</strong></div><div><small>Today</small><strong>{{ str_pad((string)$telemetry['today'],2,'0',STR_PAD_LEFT) }}</strong></div><div><small>Next 7d</small><strong>{{ str_pad((string)$telemetry['next_7_days'],2,'0',STR_PAD_LEFT) }}</strong></div><div><small>In progress</small><strong>{{ str_pad((string)$telemetry['in_progress'],2,'0',STR_PAD_LEFT) }}</strong></div><div><small>Drafts</small><strong>{{ str_pad((string)$telemetry['drafts'],2,'0',STR_PAD_LEFT) }}</strong></div>
</div>
<div class="record"><div><span class="record-label">Operational record</span><strong>{{ $telemetry['record_name'] }}</strong><span class="record-meta">{{ $telemetry['record_meta'] }}</span><span class="tag">{{ $telemetry['status'] }}</span></div><div><span class="record-label">Schedule</span><strong>{{ $telemetry['date'] }}</strong><span class="record-meta">{{ $telemetry['event_type'] }}</span></div><div><span class="record-label">Reference</span><strong class="ref">{{ $telemetry['reference'] }}</strong><span class="record-meta">{{ $telemetry['reference_meta'] }}</span></div></div>
<div class="flow"><b>JOB</b> → CUSTOMER → CAPABILITY → QUOTE → PREP → RESOURCES → FINANCE</div>
</div>
</section>
<section class="section" id="capabilities"><div class="section-head"><div><div class="eyebrow">Built around the work</div><h2>One record. A complete operational picture.</h2></div><p class="intro">The interface follows the way event work actually moves: win the job, prepare it, commit resources, execute it, then reconcile what happened.</p></div>
<div class="bento"><article class="feature large"><span class="num">01 / OPERATIONS</span><h3>Jobs become the centre of gravity.</h3><p>Customers, schedules, requirements, preparation, resources and commercial records can be understood in the context of the work they belong to.</p></article><article class="feature mini"><span class="num">02 / RESOURCES</span><h3>Know what is committed.</h3><p>Equipment, stock, purchasing and suppliers are operational inputs—not isolated registers.</p></article><article class="feature mini"><span class="num">03 / CONTROL</span><h3>Keep the business visible.</h3><p>Planning, quotes, finance and reporting provide control without burying the team in administration.</p></article></div></section>
<section class="section" id="difference"><div class="section-head"><div><div class="eyebrow">Operating difference</div><h2>Stop letting the job live in ten places.</h2></div></div><div class="compare"><article><h3>The old way</h3><ul><li>WhatsApp threads become the unofficial job record.</li><li>Quotes and preparation notes drift away from execution.</li><li>Equipment availability is checked manually.</li><li>Costs reach finance after operational decisions have already happened.</li></ul></article><article><h3>The Zazu way</h3><ul><li>The event/job remains the central operational record.</li><li>Commercial and preparation context stays close to the work.</li><li>Resources are inspected in operational context.</li><li>Financial activity has a clearer path back to the originating work.</li></ul></article></div></section>
<section class="closing"><div class="closing-box"><div><div class="eyebrow" style="color:#BFDBFE">Workspace ready</div><h2>Open the command centre.</h2><p>Continue into the Rosco ICT operational workspace.</p></div><a class="btn" href="{{ auth()->check() ? route('dashboard') : route('login') }}">Launch workspace →</a></div></section>
</main>
<footer><span>ZAZU EMP · ROSCO ICT</span><span class="footer-right">EVENT OPERATIONS / CATERING / EQUIPMENT HIRE</span></footer>
</div>
</body>
</html>