<x-app-layout>
<x-slot:title>Inventory</x-slot:title><x-slot:heading>Inventory</x-slot:heading>
<x-slot:headerAction><a href="{{ route('inventory.create') }}" class="zazu-btn zazu-btn-primary">New inventory item</a><a href="{{ route('purchasing.index') }}" class="zazu-btn zazu-btn-secondary">Purchasing</a></x-slot:headerAction>
<section class="zazu-command-band"><div><div class="zazu-eyebrow">Resources</div><h2 class="zazu-command-title">Stock control</h2><p class="zazu-command-copy">Stock on hand is derived only from recorded receipts, issues, returns and adjustments.</p></div><div class="zazu-command-meta"><div class="zazu-command-meta-label">On hand</div><div class="zazu-command-meta-value">{{ number_format($totalOnHand,2) }}</div></div></section>
<section class="zazu-metric-grid"><div class="zazu-metric-card"><div class="zazu-metric-label">Items</div><div class="zazu-metric-value">{{ $items->count() }}</div></div><div class="zazu-metric-card"><div class="zazu-metric-label">Low stock</div><div class="zazu-metric-value">{{ $lowStock }}</div></div></section>
<section class="zazu-card zazu-list mt-5"><div class="zazu-card-header"><div class="zazu-card-title">Stock register</div></div>
@forelse($items as $item)<div class="zazu-list-item"><div class="zazu-list-main"><div class="zazu-list-title">{{ $item->name }}</div><div class="zazu-list-meta">{{ $item->sku ?: 'No SKU' }} · {{ $item->unit }}</div></div><div class="zazu-list-side"><div class="zazu-side-primary">{{ number_format($item->on_hand,2) }}</div><div class="zazu-list-meta">reorder {{ number_format((float)$item->reorder_level,2) }}</div></div><div class="zazu-action-group"><form method="POST" action="{{ route('inventory.movement',$item) }}" class="flex flex-wrap gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><input type="hidden" name="type" value="receipt"><input type="number" name="quantity" min="0.01" step="0.01" placeholder="Qty" required><input type="number" name="unit_cost" min="0" step="0.01" placeholder="Cost" required><input type="date" name="movement_date" value="{{ now()->toDateString() }}" required><button class="zazu-btn zazu-btn-secondary">Receive</button></form><form method="POST" action="{{ route('inventory.movement',$item) }}" class="flex flex-wrap gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><input type="hidden" name="type" value="issue"><input type="number" name="quantity" min="0.01" step="0.01" placeholder="Qty" required><input type="number" name="unit_cost" min="0" step="0.01" placeholder="Cost" required><input type="date" name="movement_date" value="{{ now()->toDateString() }}" required><button class="zazu-btn zazu-btn-ghost">Issue</button></form></div></div>@empty<div class="zazu-empty"><div class="zazu-empty-title">No inventory items</div><p class="zazu-empty-copy">Create an item before recording stock movement.</p></div>@endforelse</section>
<section class="zazu-card zazu-list mt-5"><div class="zazu-card-header"><div class="zazu-eyebrow">Planning</div><div class="zazu-card-title mt-1">Product demand from active jobs</div></div>
@forelse($demand as $requirement)<div class="zazu-list-item"><div class="zazu-list-main"><div class="zazu-list-title">{{ $requirement->capability?->name ?? $requirement->description }}</div><div class="zazu-list-meta">{{ $requirement->event->name }}</div></div><div class="zazu-list-side"><div class="zazu-side-primary">{{ number_format((float)$requirement->quantity,2) }} {{ $requirement->unit ?: 'units' }}</div></div></div>@empty<div class="zazu-empty">No active product demand.</div>@endforelse
</section></x-app-layout>