<?php

return [
    'errors' => [
        'AUTH-001' => ['category' => 'Authentication', 'severity' => 'medium', 'status' => 401, 'headline' => 'Sign-in required.', 'message' => 'Please sign in to continue.'],
        'AUTH-002' => ['category' => 'Authentication', 'severity' => 'medium', 'status' => 419, 'headline' => 'Your session has expired.', 'message' => 'Please refresh the page or sign in again to continue.'],
        'AUTHZ-001' => ['category' => 'Authorization', 'severity' => 'high', 'status' => 403, 'headline' => 'You do not have permission for that.', 'message' => 'Your current access level does not allow this action.'],
        'VAL-001' => ['category' => 'Validation', 'severity' => 'low', 'status' => 422, 'headline' => 'Some information needs attention.', 'message' => 'Check the highlighted information and try again.'],
        'ROUTE-001' => ['category' => 'Routing', 'severity' => 'low', 'status' => 404, 'headline' => 'We could not find that page.', 'message' => 'The page may have moved, the record may no longer exist, or it may belong to another business workspace.'],
        'ROUTE-002' => ['category' => 'Routing', 'severity' => 'low', 'status' => 405, 'headline' => 'That action is not available here.', 'message' => 'This action is not available for this request.'],
        'DB-001' => ['category' => 'Database', 'severity' => 'critical', 'status' => 500, 'headline' => 'We could not load or save the requested data.', 'message' => 'Zazu could not complete a database operation. Please try again and use the reference below if the problem continues.'],
        'BUS-001' => ['category' => 'Business rule', 'severity' => 'medium', 'status' => 409, 'headline' => 'That action conflicts with the current work state.', 'message' => 'Review the record and try again.'],
        'FILE-001' => ['category' => 'File / storage', 'severity' => 'high', 'status' => 500, 'headline' => 'We could not access that file.', 'message' => 'Zazu could not access the requested file or storage. Please try again.'],
        'API-001' => ['category' => 'Integration / API', 'severity' => 'high', 'status' => 502, 'headline' => 'A connected service did not respond as expected.', 'message' => 'Please try again. The connected service may be temporarily unavailable.'],
        'CFG-001' => ['category' => 'Configuration', 'severity' => 'critical', 'status' => 500, 'headline' => 'Zazu could not use a required setting.', 'message' => 'The workspace could not complete this request. Please contact an administrator if it continues.'],
        'APP-001' => ['category' => 'Application', 'severity' => 'high', 'status' => 500, 'headline' => 'Zazu could not complete that request.', 'message' => 'We could not complete your request. Please try again, and use the reference below if the problem continues.'],
        'SYS-001' => ['category' => 'Server / infrastructure', 'severity' => 'critical', 'status' => 503, 'headline' => 'Zazu is temporarily unavailable.', 'message' => 'Please try again shortly. No technical details are exposed on this screen.'],
        'SYS-002' => ['category' => 'Server / infrastructure', 'severity' => 'medium', 'status' => 429, 'headline' => 'Please slow down for a moment.', 'message' => 'Too many requests were received. Please wait a moment and try again.'],
    ],

    'currencies' => [
        'ZAR' => 'South African rand (ZAR)',
        'BWP' => 'Botswana pula (BWP)',
        'EUR' => 'Euro (EUR)',
        'GBP' => 'Pound sterling (GBP)',
        'USD' => 'US dollar (USD)',
    ],

    'units' => [
        'service' => 'Service',
        'unit' => 'Unit',
        'item' => 'Item',
        'person' => 'Person',
        'guest' => 'Guest',
        'chair' => 'Chair',
        'table' => 'Table',
        'plate' => 'Plate',
        'hour' => 'Hour',
        'day' => 'Day',
        'kilometre' => 'Kilometre',
        'litre' => 'Litre',
        'bottle' => 'Bottle',
        'can' => 'Can',
        'crate' => 'Crate',
        'jug' => 'Jug',
        'case' => 'Case',
        'serving' => 'Serving',
    ],

    'beverage_sizes' => [
        '250ml',
        '300ml',
        '330ml',
        '440ml',
        '500ml',
        '750ml',
        '1L',
        '1.25L',
        '1.5L',
        '2L',
        '5L',
        '20L',
    ],

    'cost_categories' => [
        'Food' => 'Food',
        'Transport' => 'Transport',
        'Venue' => 'Venue',
        'Staff' => 'Staff',
        'Equipment' => 'Equipment',
        'Supplies' => 'Supplies',
        'Accommodation' => 'Accommodation',
        'Fees' => 'Fees',
        'Other' => 'Other',
    ],

    'readiness_categories' => [
        'Food' => 'Food',
        'Equipment' => 'Equipment',
        'Staff' => 'Staff',
        'Venue' => 'Venue',
        'Transport' => 'Transport',
        'Documents' => 'Documents',
        'Other' => 'Other',
    ],

    'tax' => [
        'regimes' => [
            'standard_income_tax' => 'Standard income tax',
            'turnover_tax' => 'Turnover tax',
            'other' => 'Other / specialist regime',
        ],
        'vat_statuses' => [
            'not_registered' => 'Not VAT registered',
            'registered' => 'VAT registered',
            'exempt' => 'VAT exempt / special treatment',
        ],
        'treatments' => [
            'standard' => 'Standard-rated',
            'zero_rated' => 'Zero-rated',
            'exempt' => 'Exempt',
            'out_of_scope' => 'Out of scope',
        ],
        'default_standard_rate' => '15.00',
        'sources' => [
            'sars_vat' => 'SARS VAT guidance',
        ],
    ],

    'compliance' => [
        'activity_flags' => [
            'food_handling' => 'Handles or prepares food',
            'employees' => 'Employs staff',
            'government_supply' => 'Supplies or plans to supply government',
            'tendering' => 'Prepares bids / tenders',
            'regulated_activity' => 'Other regulated activity',
        ],
        'document_types' => [
            'cipc_registration' => 'CIPC registration / incorporation proof',
            'cipc_annual_return' => 'CIPC annual return proof',
            'cipc_beneficial_ownership' => 'CIPC beneficial ownership records',
            'sars_income_tax' => 'SARS income tax registration / reference',
            'sars_tcs_good_standing' => 'SARS Tax Compliance Status (Good Standing)',
            'vat_certificate' => 'VAT registration certificate',
            'bbbee' => 'B-BBEE certificate / affidavit where applicable',
            'csd_registration' => 'Central Supplier Database (CSD) registration/report',
            'uif_registration' => 'UIF registration',
            'sdl_registration' => 'SDL registration where applicable',
            'compensation_fund' => 'Compensation Fund / COID evidence where applicable',
            'food_certificate' => 'Certificate of Acceptability for food premises where applicable',
            'business_licence' => 'Municipal business licence where applicable',
            'bank_confirmation' => 'Bank confirmation / banking proof',
            'proof_of_address' => 'Business proof of address',
            'owner_id' => 'Owner/director/member identification',
            'insurance' => 'Insurance / public liability evidence where required',
            'tender_forms' => 'Tender-specific declarations and MBD forms',
            'other' => 'Other compliance document',
        ],
    ],

    'service_categories' => [
        'Catering' => [
            'Catering',
            'Buffet',
            'Plated meals',
            'Snacks & platters',
            'Drinks & refreshments',
            'Cooldrinks',
            'Bottled water',
            'Juices',
            'Homemade juices',
            'Ginger ale',
            'Homemade beer (Mqombothi)',
        ],
        'Decor' => [
            'Decor',
            'Flowers',
            'Draping',
            'Table settings',
            'Lighting decor',
        ],
        'Sound & entertainment' => [
            'Sound system',
            'DJ',
            'MC',
            'Live music',
        ],
        'Furniture & equipment' => [
            'Chairs',
            'Tables',
            'Tents',
            'Crockery & cutlery',
            'Equipment hire',
        ],
        'Photography & video' => [
            'Photography',
            'Camera hire',
            'Videography',
        ],
        'Baking' => [
            'Wedding cake',
            'Birthday cake',
            'Cookies & treats',
        ],
        'Transport' => [
            'Passenger transport',
            'Delivery',
            'Equipment transport',
        ],
        'Staff' => [
            'Event staff',
            'Waiters',
            'Setup & cleanup',
            'Security',
        ],
        'Venue' => [
            'Venue',
            'Venue setup',
        ],
        'Other' => [],
    ],

    'permissions' => [
        'roles' => [
            'staff' => [
                'dashboard.view',
                'work.view', 'work.create', 'work.update', 'work.delete',
                'customers.view', 'customers.create', 'customers.update', 'customers.contacts.manage',
                'quotes.view', 'quotes.create', 'quotes.update', 'quotes.status',
                'finance.view', 'finance.invoice.create', 'finance.payment.create', 'finance.expense.create',
                'purchasing.view', 'purchasing.create', 'purchasing.status',
                'inventory.view', 'inventory.create', 'inventory.movement',
                'assets.view', 'assets.create', 'assets.allocate', 'assets.release',
                'suppliers.view', 'suppliers.create',
                'reports.view', 'capabilities.view',
            ],
        ],
    ],

    'job_types' => [
        'Wedding',
        'Funeral',
        'Birthday',
        'Corporate event',
        'Party',
        'Conference',
        'Meeting',
        'Equipment hire',
        'Catering order',
        'Other',
    ],
];